name: 'Rebuild data'
description: 'Rebuilds data from the COVID project API'
author: 'COVID curves'
on:
  schedule:
    - cron:  '0 */3 * * *'
  watch:
    types: [started]
jobs:
  rebuild-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Enter working directory
      run: cd /github/workspace

    - name: Get new data
      run: yarn build-data

    - uses: technote-space/get-diff-action@v1
      with:
        PREFIX_FILTER: |
          src/data

    - name: Install
      run: yarn
      if: env.GIT_DIFF

    - name: Rebuild dist
      run: yarn build

    - name: Commit files
      if: env.GIT_DIFF
      run: |
        git config --local user.email "caleb+github+action@cazzer.io"
        git config --local user.name "Caleb Brewer"
        git commit -m "rebuilding data [from action]" -a
