name: 'Rebuild data'
on:
  schedule:
    - cron:  '0 */3 * * *'
  watch:
    types: [started]
jobs:
  rebuild-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get new data
      run: yarn build-data

    - uses: technote-space/get-diff-action@v1
      id: git_diff

    - name: Install
      run: yarn
      if: steps.git_diff.outputs.diff

    - name: Rebuild dist
      run: yarn build
      if: steps.git_diff.outputs.diff

    - name: Commit files
      if: steps.git_diff.outputs.diff
      run: |
        git config --local user.email "caleb+github+action@cazzer.io"
        git config --local user.name "Caleb Brewer"
        git commit -m "rebuilding data [from action]" -a
