name: 'Rebuild data'
on:
  schedule:
    - cron:  '0 */3 * * *'
  watch:
    types: [started]
jobs:
  rebuild-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get new data
      run: yarn build-data

    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install

    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build

    - name: Commit files
      run: |
        git config --local user.email "caleb+github+action@cazzer.io"
        git config --local user.name "Caleb Brewer"
        git commit -m "rebuilding data [from action]" -a
